= Test Avec AssertJ
:doctype: book
:encoding: utf-8
:lang: fr
:icons: font
:tip-caption: pass:[&#x1F441;]
:warning-caption: pass:[&#9888]
:important-caption: pass:[&#9763;]
:note-caption: pass:[&#33;]
:caution-caption: pass:[&#9761;]
:source-highlighter: rouge
:rouge-style: github
:includedir: _includes
:author: Stéphane BETTON
:email: stéphane.betton@ag2rlamondiale.fr
:toc: left
:toclevels: 6


==  Test Exception
=== Déconseillé
Voici quelques exemples de test pour gérer les exceptions

[source,java]
----
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
import static org.assertj.core.api.AssertionsForClassTypes.catchThrowable;

class UrlHttpTest {

    @Test
    void get_Quand_UrlEstVide_Alors_UrlHttpErreur() {
        assertThatThrownBy(() -> UrlHttpBuilder.get()
                .url("")
                .build())
                .isInstanceOf(UrlHttpErreur.class)
                .hasMessage("The value(url) must not be null or blank");

    }
}
----

=== Conseillé

[source,java]
----
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
import static org.assertj.core.api.AssertionsForClassTypes.catchThrowable;

class UrlHttpTest {

    @Test
    void get_Quand_UrlEstVide_Alors_UrlHttpErreur() {
        Throwable thrown = catchThrowable(() -> UrlHttpBuilder.get()
                .url("")
                .build());
        Assertions.assertThat(thrown)
                .isInstanceOf(UrlHttpErreur.class)
                .hasMessage("The value(url) must not be null or blank");

    }
}
----
